"""add_users_count_attr_to_component

Revision ID: e03854409b8e
Revises: f586cafdb571
Create Date: 2023-05-11 02:18:57.604944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03854409b8e'
down_revision = 'f586cafdb571'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('users_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component', 'users_count')
    # ### end Alembic commands ###
